name: flutter_movies
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.5.1
  json_annotation: ^4.3.0
  flutter:
    sdk: flutter
  json_serializable: ^6.1.1
  either_dart: ^0.1.4
  http: ^0.13.4
  kiwi: ^4.0.1
  flutter_rating_bar: ^4.0.0
  infinite_scroll_pagination: ^3.1.0
  transparent_image: ^2.0.0
  url_launcher: ^6.0.17
  top_snackbar_flutter: ^1.0.2
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  build_runner: ^2.0.0
  kiwi_generator: ^4.0.1
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
